

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "CropImageView.xaml.h"




void ::Hilo::CropImageView::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///CropImageView.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///CropImageView.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'ContentRoot'
    ContentRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ContentRoot"));
    // Get the Grid named 'CropImageGrid'
    CropImageGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CropImageGrid"));
    // Get the TextBlock named 'PageTitle'
    PageTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PageTitle"));
    // Get the Image named 'Photo'
    Photo = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Photo"));
    // Get the Canvas named 'CropCanvas'
    CropCanvas = safe_cast<::Windows::UI::Xaml::Controls::Canvas^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CropCanvas"));
    // Get the ContentControl named 'CropOverlay'
    CropOverlay = safe_cast<::Windows::UI::Xaml::Controls::ContentControl^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CropOverlay"));
    // Get the VisualStateGroup named 'ApplicationViewStates'
    ApplicationViewStates = safe_cast<::Windows::UI::Xaml::VisualStateGroup^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ApplicationViewStates"));
    // Get the VisualState named 'FullScreenLandscape'
    FullScreenLandscape = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenLandscape"));
    // Get the VisualState named 'Filled'
    Filled = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Filled"));
    // Get the VisualState named 'FullScreenPortrait'
    FullScreenPortrait = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenPortrait"));
    // Get the VisualState named 'Snapped'
    Snapped = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Snapped"));
    // Get the AppBar named 'CropImageBottomAppBar'
    CropImageBottomAppBar = safe_cast<::Windows::UI::Xaml::Controls::AppBar^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CropImageBottomAppBar"));
    // Get the StackPanel named 'ResumeCropStackPanel'
    ResumeCropStackPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ResumeCropStackPanel"));
    // Get the Button named 'CancelButton'
    CancelButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CancelButton"));
    // Get the Button named 'CancelButtonNoLabel'
    CancelButtonNoLabel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CancelButtonNoLabel"));
    // Get the Button named 'SaveButton'
    SaveButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SaveButton"));
    // Get the Button named 'SaveButtonNoLabel'
    SaveButtonNoLabel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SaveButtonNoLabel"));
}

void ::Hilo::CropImageView::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Thumb^>(target))->DragDelta +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::DragDeltaEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::DragDeltaEventArgs^))&CropImageView::OnThumbDragDelta);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->SizeChanged +=
            ref new ::Windows::UI::Xaml::SizeChangedEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::SizeChangedEventArgs^))&CropImageView::OnSizeChanged);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hilo::CropImageView::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&CropImageView::OnCropRectangleTapped);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

