

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class AppBar;
                ref class Button;
                ref class GridView;
                ref class Grid;
                ref class ListView;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                namespace Primitives {
                    ref class Popup;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}

namespace Hilo
{
    partial ref class ImageView : public ::Hilo::HiloPage, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::AppBar^ ImageViewTopAppBar;
        private: ::Windows::UI::Xaml::Controls::Button^ FilmStripBackButton;
        private: ::Windows::UI::Xaml::Controls::GridView^ PhotosFilmStripGridView;
        private: ::Windows::UI::Xaml::Controls::Grid^ ContentRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ PhotoGrid;
        private: ::Windows::UI::Xaml::Controls::ListView^ SnappedPhotosFilmStripListView;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ ImageViewFileInformationPopup;
        private: ::Windows::UI::Xaml::Controls::Button^ BackButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ PageTitle;
        private: ::Windows::UI::Xaml::VisualStateGroup^ ApplicationViewStates;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenLandscape;
        private: ::Windows::UI::Xaml::VisualState^ Filled;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenPortrait;
        private: ::Windows::UI::Xaml::VisualState^ Snapped;
        private: ::Windows::UI::Xaml::Controls::AppBar^ ImageViewBottomAppBar;
        private: ::Windows::UI::Xaml::Controls::Button^ RotateButton;
        private: ::Windows::UI::Xaml::Controls::Button^ CropButton;
        private: ::Windows::UI::Xaml::Controls::Button^ CartoonizeButton;
        private: ::Windows::UI::Xaml::Controls::Button^ RotateButtonNoLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ CropButtonNoLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ CartoonizeButtonNoLabel;
    };
}

