

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "ImageBrowserView.xaml.h"




void ::Hilo::ImageBrowserView::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///ImageBrowserView.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///ImageBrowserView.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the CollectionViewSource named 'MonthGroupedItemsViewSource'
    MonthGroupedItemsViewSource = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"MonthGroupedItemsViewSource"));
    // Get the CollectionViewSource named 'YearGroupedItemsViewSource'
    YearGroupedItemsViewSource = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"YearGroupedItemsViewSource"));
    // Get the Grid named 'ContentRoot'
    ContentRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ContentRoot"));
    // Get the SemanticZoom named 'SemanticZoom'
    SemanticZoom = safe_cast<::Windows::UI::Xaml::Controls::SemanticZoom^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SemanticZoom"));
    // Get the ProgressRing named 'ProgressRing'
    ProgressRing = safe_cast<::Windows::UI::Xaml::Controls::ProgressRing^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ProgressRing"));
    // Get the ListView named 'MonthPhotosListView'
    MonthPhotosListView = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"MonthPhotosListView"));
    // Get the GridView named 'YearPhotosGridView'
    YearPhotosGridView = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"YearPhotosGridView"));
    // Get the GridView named 'MonthPhotosGridView'
    MonthPhotosGridView = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"MonthPhotosGridView"));
    // Get the Button named 'BackButton'
    BackButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BackButton"));
    // Get the TextBlock named 'PageTitle'
    PageTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PageTitle"));
    // Get the VisualStateGroup named 'ApplicationViewStates'
    ApplicationViewStates = safe_cast<::Windows::UI::Xaml::VisualStateGroup^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ApplicationViewStates"));
    // Get the VisualState named 'FullScreenLandscape'
    FullScreenLandscape = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenLandscape"));
    // Get the VisualState named 'Filled'
    Filled = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Filled"));
    // Get the VisualState named 'FullScreenPortrait'
    FullScreenPortrait = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenPortrait"));
    // Get the VisualState named 'Snapped'
    Snapped = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Snapped"));
    // Get the AppBar named 'ImageBrowserViewBottomAppBar'
    ImageBrowserViewBottomAppBar = safe_cast<::Windows::UI::Xaml::Controls::AppBar^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageBrowserViewBottomAppBar"));
    // Get the Button named 'RotateButton'
    RotateButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"RotateButton"));
    // Get the Button named 'CropButton'
    CropButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CropButton"));
    // Get the Button named 'CartoonizeButton'
    CartoonizeButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CartoonizeButton"));
    // Get the Button named 'RotateButtonNoLabel'
    RotateButtonNoLabel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"RotateButtonNoLabel"));
    // Get the Button named 'CropButtonNoLabel'
    CropButtonNoLabel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CropButtonNoLabel"));
    // Get the Button named 'CartoonizeButtonNoLabel'
    CartoonizeButtonNoLabel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CartoonizeButtonNoLabel"));
}

void ::Hilo::ImageBrowserView::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::SemanticZoom^>(target))->ViewChangeCompleted +=
            ref new ::Windows::UI::Xaml::Controls::SemanticZoomViewChangedEventHandler(this, (void (::Hilo::ImageBrowserView::*)(Platform::Object^, Windows::UI::Xaml::Controls::SemanticZoomViewChangedEventArgs^))&ImageBrowserView::OnViewChangeCompleted);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::ListViewBase^>(target))->ItemClick +=
            ref new ::Windows::UI::Xaml::Controls::ItemClickEventHandler(this, (void (::Hilo::ImageBrowserView::*)(Platform::Object^, Windows::UI::Xaml::Controls::ItemClickEventArgs^))&ImageBrowserView::OnPhotoItemClicked);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::Hilo::ImageBrowserView::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&ImageBrowserView::OnZoomedOutGridPointerEntered);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::ListViewBase^>(target))->ItemClick +=
            ref new ::Windows::UI::Xaml::Controls::ItemClickEventHandler(this, (void (::Hilo::ImageBrowserView::*)(Platform::Object^, Windows::UI::Xaml::Controls::ItemClickEventArgs^))&ImageBrowserView::OnPhotoItemClicked);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hilo::ImageBrowserView::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ImageBrowserView::GoBack);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

